#!/usr/bin/env python3
"""Writes THIRD-PARTY-NOTICES.md: every crate that goes into the shipped programs, with its
licence and the licence texts found in its source, from `cargo metadata` alone (no cargo-about).

    scripts/third-party-notices.py [OUTPUT]      # default: THIRD-PARTY-NOTICES.md in the repo root

Run it with the dependencies fetched (a build or `cargo fetch` does that), and commit the result
whenever Cargo.lock changes. Only crates reached through normal dependencies on the Linux target
are listed: dev and build-only crates are not in what is shipped.
"""
import hashlib
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = "x86_64-unknown-linux-gnu"
LICENCE_NAMES = ("license", "licence", "copying", "notice", "unlicense")


def metadata():
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked", "--filter-platform", TARGET],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    return json.loads(out)


def shipped(meta):
    """Ids of the packages reached from the workspace members through normal dependencies."""
    nodes = {node["id"]: node for node in meta["resolve"]["nodes"]}
    seen, todo = set(), list(meta["workspace_members"])
    while todo:
        pid = todo.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            if any(kind["kind"] is None for kind in dep["dep_kinds"]):
                todo.append(dep["pkg"])
    return seen


def licence_files(package):
    """The crate's own licence files, else those of the workspace it sits in (dioxus, blitz and
    others keep one copy at the repository root)."""
    folder = pathlib.Path(package["manifest_path"]).parent
    for level in range(5):
        own = level == 0
        manifest = folder / "Cargo.toml"
        root = manifest.is_file() and "[workspace]" in manifest.read_text(errors="replace")
        if own or root:
            found = [
                path for path in sorted(folder.iterdir())
                if path.is_file() and path.name.lower().startswith(LICENCE_NAMES)
            ]
            if found:
                return found
        folder = folder.parent
    return []


def main():
    out_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "THIRD-PARTY-NOTICES.md"
    meta = metadata()
    members = set(meta["workspace_members"])
    wanted = shipped(meta) - members
    packages = sorted(
        (p for p in meta["packages"] if p["id"] in wanted), key=lambda p: (p["name"], p["version"])
    )
    texts = {}  # sha -> (text, [crate labels])
    by_expression = {}  # licence expression -> digests of a crate that has the files
    missing = []  # crates whose package ships no licence file
    lines = [
        "# Third-party notices",
        "",
        "anyview is MIT OR Apache-2.0 (see LICENSE-MIT and LICENSE-APACHE). It is built from the",
        "open source crates listed below, each under the licence shown. The licence texts follow the",
        "list. The text-highlighting grammars of syntect's default set (Sublime Packages) are compiled",
        "in under their own permissive licences, listed in the syntect crate's repository.",
        "",
        "The program also loads system libraries of the machine it runs on, dynamically and not",
        "bundled; among them libasound (ALSA), LGPL-2.1, which only the built-in audio player uses",
        "to reach the sound card.",
        "",
        "Generated by scripts/third-party-notices.py from `cargo metadata`; do not edit by hand.",
        "",
        f"## Crates ({len(packages)})",
        "",
    ]
    for package in packages:
        label = f"{package['name']} {package['version']}"
        licence = package.get("license") or "see licence files"
        repo = package.get("repository") or ""
        lines.append(f"- {label}: {licence}" + (f" ({repo})" if repo else ""))
        digests = []
        for path in licence_files(package):
            data = path.read_text(errors="replace").strip()
            digest = hashlib.sha256(data.encode()).hexdigest()
            texts.setdefault(digest, (data, []))[1].append(label)
            digests.append(digest)
        if digests:
            by_expression.setdefault(licence, digests)
        else:
            missing.append((label, licence))
    # A crate published without its licence files gets the standard text the same expression has
    # elsewhere in the tree; only the copyright holder's line can differ, and that is in its manifest.
    for label, licence in missing:
        for digest in by_expression.get(licence, []):
            texts[digest][1].append(label + " (standard text)")
    lines += ["", f"## Licence texts ({len(texts)})", ""]
    for index, (data, users) in enumerate(
        sorted(texts.values(), key=lambda item: item[1][0]), start=1
    ):
        lines += [f"### {index}. Used by: {', '.join(users)}", "", "```text", data, "```", ""]
    out_path.write_text("\n".join(lines))
    print(f"{out_path}: {len(packages)} crates, {len(texts)} distinct licence texts")


main()
